---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-test
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh:git@github.com:nishioka-shinji/k8s-test.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-test
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: k8s-test
  timeout: 3m0s
  wait: true
