---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: imgproxy
  namespace: imgproxy
spec:
  interval: 1m0s
  url: https://helm.imgproxy.net/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: imgproxy
  namespace: imgproxy
spec:
  chart:
    spec:
      chart: imgproxy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: imgproxy
      version: 0.9.0
  interval: 1m0s
