---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: imgproxy
  namespace: imgproxy
spec:
  interval: 1m0s
  url: https://helm.imgproxy.net/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: imgproxy
  namespace: imgproxy
spec:
  chart:
    spec:
      chart: imgproxy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: imgproxy
      version: 0.9.0
  interval: 1m0s
  values:
    features:
      # TODO: のちほど設定
      # urlSignature:
      #   key:
      #   salt:
      compression:
        quality: "100"
      presets:
        definitions: thumb=rs:fill:400:400/format:webp
        onlyPresets: true
      # TODO: のちほど設定
      # aws:
      #   enabled: true
      #   accountId:
      #   accessKeyId:
      #   secretAccessKey:
      #   iamRoleName:
      #   s3Region: ap-northeast-1
